version: '3'

services:
  tascc-api:
    image: tascc-api
    build:
      context: .
      dockerfile: Test.Dockerfile
    environment:
      - NOVU_KEY=6ae8983a9c3151d3c9cc1773c911521c
      - MONGODB_URL=mongodb://mongodb:27017/system
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
      - JWT_REFRESH_EXPIRATION_DAYS=30
      - JWT_RESET_PASSWORD_EXPIRATION_MINUTES=100
      - JWT_VERIFY_EMAIL_EXPIRATION_MINUTES=10
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/tascc-api
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
